service: product-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:ap-south-1:749453116506:table/products
        - arn:aws:dynamodb:ap-south-1:749453116506:table/stocks

functions:
  getProductsList:
    handler: src/products.getProductsList
    events:
      - http:
          path: products
          method: get
          cors:
            origin: "*"
  getProductsById:
    handler: src/products.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors:
            origin: "*"
  addProduct:
    handler: src/products.createProduct
    events:
      - http:
          path: products
          method: post
          cors:
            origin: "*"
  updateStock:
    handler: src/stocks.updateStock
    events:
      - http:
          path: stocks
          method: put
          cors:
            origin: "*"

resources:
  Resources:
    ProductsResource:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    StocksResource:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: stocks
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
