app: aws-node-project
service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  tracing: {}
  httpApi:
    cors: true
    authorizers:
      authorizerForImport:
        type: request
        functionArn: arn:aws:lambda:ap-south-1:749453116506:function:authorization-service-dev-basicAuthorizer

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::epam-uploaded/uploaded/*"
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:ap-south-1:749453116506:catalogItemsQueue"

functions:
  importProductsFile:
    handler: src/upload.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          authorizer:
            name: authorizerForImport
  importFileParser:
    handler: src/upload.importFileParser
    events:
      - s3:
          bucket: epam-uploaded
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    catalogItemsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "catalogItemsQueue"
